name: news_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  dio: ^5.0.3
  equatable: ^2.0.5
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_ui_auth: ^1.1.17
  firebase_ui_oauth_google: ^1.0.24
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.1
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
